"""add testing phases

Revision ID: 20c19e9e0a91
Revises: c2d3e4f5a6b7
Create Date: 2026-03-13 16:41:00.258248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c19e9e0a91'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # Create testing_phase table — skip if it already exists from a partial run
    try:
        op.create_table('testing_phase',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('phase_type', sa.String(length=30), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('start_date', sa.Date(), nullable=True),
            sa.Column('end_date', sa.Date(), nullable=True),
            sa.Column('active', sa.Boolean(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('team_organization_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['team_organization_id'], ['team_organization.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    except Exception:
        pass

    with op.batch_alter_table('fitness_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testing_phase_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_fitness_record_testing_phase', 'testing_phase', ['testing_phase_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.create_index('ix_workout_plans_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('user_session_completions', schema=None) as batch_op:
        batch_op.create_index('ix_user_session_completions_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('user_schedule_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_user_schedule_preferences_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_team_org', ['team_organization_id'], unique=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('track_workout_weeks', schema=None) as batch_op:
        batch_op.create_index('ix_track_workout_weeks_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('tournament_rsvp', schema=None) as batch_op:
        batch_op.create_index('ix_tournament_rsvp_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.create_index('ix_tournament_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('throw', schema=None) as batch_op:
        batch_op.create_index('ix_throw_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('theory_video', schema=None) as batch_op:
        batch_op.create_index('ix_theory_video_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('theory_topic', schema=None) as batch_op:
        batch_op.create_index('ix_theory_topic_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('theory_tag', schema=None) as batch_op:
        batch_op.create_index('ix_theory_tag_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('theory_section', schema=None) as batch_op:
        batch_op.create_index('ix_theory_section_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('smart_goals', schema=None) as batch_op:
        batch_op.create_index('ix_smart_goals_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('session_rsvp', schema=None) as batch_op:
        batch_op.create_index('ix_session_rsvp_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('session_plan', schema=None) as batch_op:
        batch_op.create_index('ix_session_plan_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('session_component', schema=None) as batch_op:
        batch_op.create_index('ix_session_component_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('scouting_report', schema=None) as batch_op:
        batch_op.create_index('ix_scouting_report_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('scouting_clip', schema=None) as batch_op:
        batch_op.create_index('ix_scouting_clip_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('schedule_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_sessions_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('saved_drill', schema=None) as batch_op:
        batch_op.create_index('ix_saved_drill_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('pull', schema=None) as batch_op:
        batch_op.create_index('ix_pull_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.create_index('ix_point_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('player_position', schema=None) as batch_op:
        batch_op.create_index('ix_player_position_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('player_point_stats', schema=None) as batch_op:
        batch_op.create_index('ix_player_point_stats_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index('ix_player_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('play_tag', schema=None) as batch_op:
        batch_op.create_index('ix_play_tag_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('play_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_play_assignment_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('play', schema=None) as batch_op:
        batch_op.create_index('ix_play_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('phase_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_phase_schedules_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('phase_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_phase_metrics_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('opponent_player', schema=None) as batch_op:
        batch_op.create_index('ix_opponent_player_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('off_season_phases', schema=None) as batch_op:
        batch_op.create_index('ix_off_season_phases_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('line_up', schema=None) as batch_op:
        batch_op.create_index('ix_line_up_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('line_template_player', schema=None) as batch_op:
        batch_op.create_index('ix_line_template_player_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('line_template', schema=None) as batch_op:
        batch_op.create_index('ix_line_template_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('game_player', schema=None) as batch_op:
        batch_op.create_index('ix_game_player_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('game_day_player_stats', schema=None) as batch_op:
        batch_op.create_index('ix_game_day_player_stats_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('game_day_event', schema=None) as batch_op:
        batch_op.create_index('ix_game_day_event_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index('ix_game_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('formation', schema=None) as batch_op:
        batch_op.create_index('ix_formation_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('fitness_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('ix_fitness_record_team_org', ['team_organization_id'], unique=False)
        batch_op.drop_column('testing_phase_id')

    with op.batch_alter_table('fitness_metric', schema=None) as batch_op:
        batch_op.create_index('ix_fitness_metric_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('export_log', schema=None) as batch_op:
        batch_op.create_index('ix_export_log_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index('ix_event_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('drill_frame', schema=None) as batch_op:
        batch_op.create_index('ix_drill_frame_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('drill', schema=None) as batch_op:
        batch_op.create_index('ix_drill_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('cutting_skill', schema=None) as batch_op:
        batch_op.create_index('ix_cutting_skill_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('clip_tag', schema=None) as batch_op:
        batch_op.create_index('ix_clip_tag_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('clip_point_segments', schema=None) as batch_op:
        batch_op.create_index('ix_clip_point_segments_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('clip_annotation', schema=None) as batch_op:
        batch_op.create_index('ix_clip_annotation_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.create_index('ix_clip_team_org', ['team_organization_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_team_org', ['team_organization_id'], unique=False)

    op.drop_table('testing_phase')
    # ### end Alembic commands ###
