"""Add video source field to clips

Revision ID: 443f4ea75519
Revises: 
Create Date: 2025-05-27 16:18:22.829421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f4ea75519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Safely add video_source to clip for existing rows (Postgres-friendly)
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_source', sa.String(length=20), nullable=True, server_default='upload'))

    # Remove the default and enforce NOT NULL
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.alter_column('video_source', nullable=False, server_default=None)

    # Foreign key update for session_component.drill_id -> saved_drill.id (ON DELETE CASCADE)
    # Postgres needs an explicit constraint name to drop. If you know it, uncomment and use it:
    # op.drop_constraint('session_component_drill_id_fkey', 'session_component', type_='foreignkey')
    # op.create_foreign_key(
    #     'session_component_drill_id_fkey',
    #     'session_component',
    #     'saved_drill',
    #     ['drill_id'],
    #     ['id'],
    #     ondelete='CASCADE'
    # )

    # If you don't know the existing name, here is a Postgres-safe block that drops the FK on drill_id if it exists:
    op.execute("""
    DO $$
    DECLARE
      fk_name text;
    BEGIN
      SELECT tc.constraint_name INTO fk_name
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
      WHERE tc.table_name='session_component'
        AND tc.constraint_type='FOREIGN KEY'
        AND kcu.column_name='drill_id'
      LIMIT 1;

      IF fk_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE session_component DROP CONSTRAINT ' || quote_ident(fk_name);
      END IF;
    END $$;
    """)

    op.create_foreign_key(
        'fk_session_component_drill_id_saved_drill',
        'session_component',
        'saved_drill',
        ['drill_id'],
        ['id'],
        ondelete='CASCADE'
    )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'saved_drill', ['drill_id'], ['id'])

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_column('video_source')

    # ### end Alembic commands ###
