"""Add video source field to clips

Revision ID: 443f4ea75519
Revises: 
Create Date: 2025-05-27 16:18:22.829421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f4ea75519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_source', sa.String(length=20), nullable=False))

    with op.batch_alter_table('session_component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'saved_drill', ['drill_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_component', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'saved_drill', ['drill_id'], ['id'])

    with op.batch_alter_table('clip', schema=None) as batch_op:
        batch_op.drop_column('video_source')

    # ### end Alembic commands ###
