"""Add majority_gender to Point

Revision ID: 7116f57dd6ec
Revises: 71b8b550f6ed
Create Date: 2026-02-16 12:01:50.262183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7116f57dd6ec'
down_revision = '71b8b550f6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('majority_gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_column('majority_gender')

    # ### end Alembic commands ###
