"""Add division to TeamOrganization

Revision ID: 71b8b550f6ed
Revises: e3e44e60d100
Create Date: 2026-02-16 11:48:48.502778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b8b550f6ed'
down_revision = 'e3e44e60d100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_organization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_organization', schema=None) as batch_op:
        batch_op.drop_column('division')

    # ### end Alembic commands ###
