"""Add share token fields to SessionPlan

Revision ID: d2ca975d8afa
Revises: 441730e8e830
Create Date: 2026-03-05 13:59:28.494654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ca975d8afa'
down_revision = '441730e8e830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('share_token_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_session_plan_share_token'), ['share_token'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('session_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_plan_share_token'))
        batch_op.drop_column('share_token_expires')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
